In [29]:
from tensorflow.keras.models import load_model
import pandas as pd
from sklearn.metrics import confusion_matrix
import joblib
import numpy as np

In [14]:
model = load_model("best_model2.h5")

In [15]:
features = pd.read_csv("distance_test.csv")
labels = pd.read_csv("distance_test_target.csv")

In [16]:
scaler = joblib.load("scaler_final.save")

In [17]:
features = scaler.transform(features)

In [18]:
model.evaluate(features, labels)

400/400 [==============================] - 2s 4ms/step - loss: 0.3994 - accuracy: 0.9592


[0.399356871843338, 0.9592108130455017]

In [25]:
actualValue = labels.values.argmax(axis=1)

In [42]:
actualValue = actualValue.reshape(12773, 1)

In [41]:
actualValue

array([[ 0,  0,  0, ..., 26, 26, 26]], dtype=int64)

In [21]:
prediction = model.predict(features)

400/400 [==============================] - 1s 2ms/step


In [30]:
pred = np.argmax(prediction, axis=1)

In [37]:
pred = pred.reshape(1, 12773)

array([[ 0, 19,  0, ..., 26, 26, 26]], dtype=int64)

In [43]:
confusion_matrix(actualValue, pred)

array([[436,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,  50,  12,   0,   0,   0,   0,   0,
          0],
       [  0, 472,   0,   0,   2,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   7,   0,   0,   0,   0,   0,  18,   0,   0,   0,   0,
          0],
       [  0,   0, 482,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   2,   0,   0,   2,   0,   0,   1,   0,   0,   0,   0,
          0],
       [  0,   0,   0, 419,   1,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   1,  73,   0,   0,   0,   0,   0,   0,   5,
          0],
       [  0,   0,   0,   0, 457,   9,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   4,   0,  23,   1,   0,   0,   2,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   1, 449,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,  43,   0,   0,   0,   1,   0,   0,   0,   0,
          0],
       [  0,   0,   0,   0,   0,   0, 54